### ISSUE TITLE
[Quick Question] - Inclusion of aspect-ratio plugin

### ISSUE THREAD

**Issue by armenr** [posva/vite-tailwind-starter#228]
Hi @posva - I'm a HUGE fan of your work (Pinia = <3).

While I was inspecting this starter template, I noticed you are installing the tailwind aspect-ratio plugin. When searching through the code, I see no direct references or inclusion of the term `aspect` in any of the class utilities or HTML elements being rendered.

Out of curiosity (not a criticism), what is the purpose of including the plugin? Is there something automatic which it is doing/providing simply by being included?

Thanks again!
_Armen (a huge fan)

**Comment by posva** [comment]
Thanks! Sorry I missed your comment. I honestly don't know why I added the plugin anymore 😓
