### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by husayt** [posva/vite-tailwind-starter#25]
bundle generated with build doesn't recognise any of the routes

**Comment by posva** [comment]
I imagine you need to configure the server to redirect to `index.html`, like with vue-router v3 (https://router.vuejs.org/guide/essentials/history-mode.html)

Please, when opening issues provide more information, this could mean so many different things

**Comment by husayt** [comment]
Thanks @posva. I realised the issue is not with this demo, but probably with vite itself or my changes. So I created a detailed issue [here](https://github.com/vitejs/vite/issues/339)
