### ISSUE TITLE
Purge with tailwindcss/ui

### ISSUE THREAD

**Issue by web2033** [posva/vite-tailwind-starter#74]
I'm trying on an empty project with `@tailwindcss/ui` but it adds ~70kb to CSS

(the second build with `plugins: [require('@tailwindcss/ui')]` commented out.

Anyone else has the same issue?

![2020-08-08_230701](https://user-images.githubusercontent.com/11320080/89719255-157a0f80-d9cf-11ea-909a-badc2d1b9309.png)

**Comment by posva** [comment]
Cannot reproduce on this template. Maybe you are using that amount of CSS

**Comment by web2033** [comment]
@posva I just tried without changing anything in this starter:
output css -> 12.02kb

after `yarn add @tailwindcss/ui` and adding `plugins: [require('@tailwindcss/ui')],`
output css -> 85.64kb

Most of the styles related to "prose".
I suspect this related to their new add-on https://github.com/tailwindlabs/tailwindcss-typography
