### ISSUE TITLE
Error in Codesandbox

### ISSUE THREAD

**Issue by web2033** [posva/vite-tailwind-starter#75]
Tried to test it on [codesandbox](https://codesandbox.io/s/blue-brook-plcsk) and got an error. Any ideas?

![2020-08-09_213407](https://user-images.githubusercontent.com/11320080/89739278-17ec7000-da88-11ea-9660-9cb3309eca33.png)

**Comment by posva** [comment]
probably a bug in some of the parsers expecting `import` in a specific way. You should report the bug to CodeSandbox

**Comment by cliqer** [comment]
@web2033 check my version:
[https://codesandbox.io/s/vite-tailwind-starter-04mrv?file=/src/components/router.js](https://codesandbox.io/s/vite-tailwind-starter-04mrv?file=/src/components/router.js)
Maybe you can find the reason it works

**Comment by web2033** [comment]
@cliqer thanks, I see it kinda expects "import" only on a top-level, but I do not why your example is working then...
Reversing it like this `routes: !import.meta.hot ? [] : routes` didn't help. I only see this pattern in Vite and Snowpack

**Comment by SaraVieira** [comment]
👋 

The error was indeed a codesandbox error, we were not redirecting anything that had vite to node sandboxes

All vite sandboxes will now run in containers and so it should be like local and no more of these issue :)

**Comment by posva** [comment]
Thank you Sara!
