### ISSUE TITLE
Adding tailwindcss/ui slows down Dev Tools

### ISSUE THREAD

**Issue by web2033** [posva/vite-tailwind-starter#86]
Hi. I see a big difference in the time it takes to render styles panel in Chrome Dev Tools after enabling **tailwindcss/ui** plugin.

Inspect any element and styles shows up in panel:
- without plugin ~ 4s
- with the plugin enabled ~ 30-40s or even crashes the browser.

What can be the cause?

**Comment by posva** [comment]
I have no idea but this is a boilerplate, you might want to open an issue on the package repository instead.
